# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 958)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.idtext1 = QtWidgets.QLineEdit(self.centralwidget)
        self.idtext1.setGeometry(QtCore.QRect(120, 40, 121, 31))
        self.idtext1.setObjectName("idtext1")
        self.idtext2 = QtWidgets.QLineEdit(self.centralwidget)
        self.idtext2.setGeometry(QtCore.QRect(560, 40, 111, 31))
        self.idtext2.setObjectName("idtext2")
        self.loadbutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.loadbutton1.setGeometry(QtCore.QRect(130, 80, 93, 28))
        self.loadbutton1.setObjectName("loadbutton1")
        self.loadbutton2 = QtWidgets.QPushButton(self.centralwidget)
        self.loadbutton2.setGeometry(QtCore.QRect(570, 80, 93, 28))
        self.loadbutton2.setObjectName("loadbutton2")
        self.copybutton = QtWidgets.QPushButton(self.centralwidget)
        self.copybutton.setGeometry(QtCore.QRect(350, 50, 93, 28))
        self.copybutton.setObjectName("copybutton")
        self.nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.nextbutton.setGeometry(QtCore.QRect(350, 90, 93, 28))
        self.nextbutton.setObjectName("nextbutton")
        self.pic1_1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1_1.setGeometry(QtCore.QRect(30, 160, 321, 241))
        self.pic1_1.setObjectName("pic1_1")
        self.pathtext = QtWidgets.QLineEdit(self.centralwidget)
        self.pathtext.setGeometry(QtCore.QRect(120, 0, 551, 31))
        self.pathtext.setObjectName("pathtext")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 120, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 120, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pic1_2 = QtWidgets.QLabel(self.centralwidget)
        self.pic1_2.setGeometry(QtCore.QRect(30, 400, 321, 241))
        self.pic1_2.setObjectName("pic1_2")
        self.pic1_3 = QtWidgets.QLabel(self.centralwidget)
        self.pic1_3.setGeometry(QtCore.QRect(30, 640, 321, 241))
        self.pic1_3.setObjectName("pic1_3")
        self.pic2_1 = QtWidgets.QLabel(self.centralwidget)
        self.pic2_1.setGeometry(QtCore.QRect(440, 160, 321, 241))
        self.pic2_1.setObjectName("pic2_1")
        self.pic2_3 = QtWidgets.QLabel(self.centralwidget)
        self.pic2_3.setGeometry(QtCore.QRect(440, 640, 321, 241))
        self.pic2_3.setObjectName("pic2_3")
        self.pic2_2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2_2.setGeometry(QtCore.QRect(440, 400, 321, 241))
        self.pic2_2.setObjectName("pic2_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.openpath = QtWidgets.QAction(MainWindow)
        self.openpath.setObjectName("openpath")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.menufile.addAction(self.openpath)
        self.menufile.addSeparator()
        self.menufile.addAction(self.exit)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.copybutton.clicked.connect(MainWindow.copyfile)
        self.nextbutton.clicked.connect(MainWindow.nextdir)
        self.loadbutton1.clicked.connect(MainWindow.id1loadOnclick)
        self.loadbutton2.clicked.connect(MainWindow.id2loadOnclick)
        self.pushButton.clicked.connect(MainWindow.id1delOnclick)
        self.pushButton_2.clicked.connect(MainWindow.id2delOnclick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "cluster_v1"))
        self.loadbutton1.setText(_translate("MainWindow", "load"))
        self.loadbutton2.setText(_translate("MainWindow", "load"))
        self.copybutton.setText(_translate("MainWindow", "copy"))
        self.nextbutton.setText(_translate("MainWindow", "next"))
        self.pic1_1.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "del"))
        self.pushButton_2.setText(_translate("MainWindow", "del"))
        self.pic1_2.setText(_translate("MainWindow", "TextLabel"))
        self.pic1_3.setText(_translate("MainWindow", "TextLabel"))
        self.pic2_1.setText(_translate("MainWindow", "TextLabel"))
        self.pic2_3.setText(_translate("MainWindow", "TextLabel"))
        self.pic2_2.setText(_translate("MainWindow", "TextLabel"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.openpath.setText(_translate("MainWindow", "open"))
        self.exit.setText(_translate("MainWindow", "quit"))

