# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.path = QtWidgets.QLabel(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.path.setObjectName("path")
        self.pathshow = QtWidgets.QLabel(self.centralwidget)
        self.pathshow.setGeometry(QtCore.QRect(120, 30, 541, 31))
        self.pathshow.setText("")
        self.pathshow.setObjectName("pathshow")
        self.pic_1 = QtWidgets.QLabel(self.centralwidget)
        self.pic_1.setGeometry(QtCore.QRect(20, 130, 241, 321))
        self.pic_1.setObjectName("pic_1")
        self.pic_2 = QtWidgets.QLabel(self.centralwidget)
        self.pic_2.setGeometry(QtCore.QRect(270, 130, 241, 321))
        self.pic_2.setObjectName("pic_2")
        self.pic_3 = QtWidgets.QLabel(self.centralwidget)
        self.pic_3.setGeometry(QtCore.QRect(520, 130, 241, 321))
        self.pic_3.setObjectName("pic_3")
        self.type_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.type_1.setGeometry(QtCore.QRect(60, 80, 113, 21))
        self.type_1.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.type_1.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.type_1.setMaxLength(1)
        self.type_1.setObjectName("type_1")
        self.type_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.type_2.setGeometry(QtCore.QRect(320, 80, 113, 21))
        self.type_2.setMaxLength(1)
        self.type_2.setObjectName("type_2")
        self.type_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.type_3.setGeometry(QtCore.QRect(590, 80, 113, 21))
        self.type_3.setMaxLength(1)
        self.type_3.setObjectName("type_3")
        self.picname_1 = QtWidgets.QLabel(self.centralwidget)
        self.picname_1.setGeometry(QtCore.QRect(40, 470, 201, 31))
        self.picname_1.setObjectName("picname_1")
        self.picname_2 = QtWidgets.QLabel(self.centralwidget)
        self.picname_2.setGeometry(QtCore.QRect(290, 470, 201, 31))
        self.picname_2.setObjectName("picname_2")
        self.picname_3 = QtWidgets.QLabel(self.centralwidget)
        self.picname_3.setGeometry(QtCore.QRect(540, 470, 201, 31))
        self.picname_3.setObjectName("picname_3")
        self.loadpicname = QtWidgets.QLineEdit(self.centralwidget)
        self.loadpicname.setGeometry(QtCore.QRect(30, 530, 331, 31))
        self.loadpicname.setObjectName("loadpicname")
        self.loadbut = QtWidgets.QPushButton(self.centralwidget)
        self.loadbut.setGeometry(QtCore.QRect(450, 530, 271, 31))
        self.loadbut.setObjectName("loadbut")
        self.tipcontent = QtWidgets.QLabel(self.centralwidget)
        self.tipcontent.setGeometry(QtCore.QRect(30, 600, 631, 31))
        self.tipcontent.setObjectName("tipcontent")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 590, 271, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menuactionopen = QtWidgets.QAction(MainWindow)
        self.menuactionopen.setObjectName("menuactionopen")
        self.menuactionquit = QtWidgets.QAction(MainWindow)
        self.menuactionquit.setObjectName("menuactionquit")
        self.menu.addAction(self.menuactionopen)
        self.menu.addSeparator()
        self.menu.addAction(self.menuactionquit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.loadbut.clicked.connect(MainWindow.loadpic)
        self.pushButton.clicked.connect(MainWindow.savebut)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.path.setText(_translate("MainWindow", "path:"))
        self.pic_1.setText(_translate("MainWindow", "TextLabel"))
        self.pic_2.setText(_translate("MainWindow", "TextLabel"))
        self.pic_3.setText(_translate("MainWindow", "TextLabel"))
        self.picname_1.setText(_translate("MainWindow", "TextLabel"))
        self.picname_2.setText(_translate("MainWindow", "TextLabel"))
        self.picname_3.setText(_translate("MainWindow", "TextLabel"))
        self.loadbut.setText(_translate("MainWindow", "load"))
        self.loadbut.setShortcut(_translate("MainWindow", "Enter"))
        self.tipcontent.setText(_translate("MainWindow", "注：其他->0   红外图片->1    彩色图片->2    黑白图片->3"))
        self.pushButton.setText(_translate("MainWindow", "save"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuactionopen.setText(_translate("MainWindow", "open"))
        self.menuactionquit.setText(_translate("MainWindow", "quit"))

