# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageManage_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picshowLabel = QtWidgets.QLabel(self.centralwidget)
        self.picshowLabel.setGeometry(QtCore.QRect(10, 10, 541, 641))
        self.picshowLabel.setText("")
        self.picshowLabel.setObjectName("picshowLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 690, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 750, 91, 31))
        self.label_3.setObjectName("label_3")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(590, 220, 71, 51))
        self.startbutton.setObjectName("startbutton")
        self.testbutton = QtWidgets.QPushButton(self.centralwidget)
        self.testbutton.setGeometry(QtCore.QRect(710, 220, 71, 51))
        self.testbutton.setObjectName("testbutton")
        self.savebutton = QtWidgets.QPushButton(self.centralwidget)
        self.savebutton.setGeometry(QtCore.QRect(590, 290, 71, 51))
        self.savebutton.setObjectName("savebutton")
        self.skipbutton = QtWidgets.QPushButton(self.centralwidget)
        self.skipbutton.setGeometry(QtCore.QRect(590, 350, 71, 51))
        self.skipbutton.setObjectName("skipbutton")
        self.fixbutton = QtWidgets.QPushButton(self.centralwidget)
        self.fixbutton.setGeometry(QtCore.QRect(590, 410, 71, 51))
        self.fixbutton.setObjectName("fixbutton")
        self.nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.nextbutton.setGeometry(QtCore.QRect(590, 470, 71, 51))
        self.nextbutton.setObjectName("nextbutton")
        self.facepathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.facepathEdit.setGeometry(QtCore.QRect(140, 690, 411, 31))
        self.facepathEdit.setObjectName("facepathEdit")
        self.txtoutpathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.txtoutpathEdit.setGeometry(QtCore.QRect(142, 750, 411, 31))
        self.txtoutpathEdit.setObjectName("txtoutpathEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 60, 141, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 20, 111, 31))
        self.label_4.setObjectName("label_4")
        self.startnumEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startnumEdit.setGeometry(QtCore.QRect(700, 100, 71, 31))
        self.startnumEdit.setObjectName("startnumEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 100, 111, 31))
        self.label_5.setObjectName("label_5")
        self.folderlenLabel = QtWidgets.QLabel(self.centralwidget)
        self.folderlenLabel.setGeometry(QtCore.QRect(701, 20, 81, 31))
        self.folderlenLabel.setObjectName("folderlenLabel")
        self.tagfolderLabel = QtWidgets.QLabel(self.centralwidget)
        self.tagfolderLabel.setGeometry(QtCore.QRect(730, 60, 72, 31))
        self.tagfolderLabel.setObjectName("tagfolderLabel")
        self.loadbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loadbutton.setGeometry(QtCore.QRect(590, 160, 101, 51))
        self.loadbutton.setObjectName("loadbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.startbutton.clicked.connect(MainWindow.startOnclicked)
        self.testbutton.clicked.connect(MainWindow.testOnclicked)
        self.savebutton.clicked.connect(MainWindow.saveOnclicked)
        self.skipbutton.clicked.connect(MainWindow.skipOnclicked)
        self.fixbutton.clicked.connect(MainWindow.fixOnclicked)
        self.nextbutton.clicked.connect(MainWindow.nextOnclicked)
        self.loadbutton.clicked.connect(MainWindow.loadOnclicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "facepath:"))
        self.label_3.setText(_translate("MainWindow", "txtoutpath:"))
        self.startbutton.setText(_translate("MainWindow", "开始"))
        self.testbutton.setText(_translate("MainWindow", "检查"))
        self.savebutton.setText(_translate("MainWindow", "保存"))
        self.skipbutton.setText(_translate("MainWindow", "跳过"))
        self.fixbutton.setText(_translate("MainWindow", "修改"))
        self.nextbutton.setText(_translate("MainWindow", "下一张"))
        self.label.setText(_translate("MainWindow", "当前所在文件夹ID："))
        self.label_4.setText(_translate("MainWindow", "文件夹目录长度："))
        self.startnumEdit.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "开始文件夹ID："))
        self.folderlenLabel.setText(_translate("MainWindow", "0"))
        self.tagfolderLabel.setText(_translate("MainWindow", "0"))
        self.loadbutton.setText(_translate("MainWindow", "加载文件夹"))

